-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Erstellungszeit: 27. Mrz 2015 um 14:59
-- Server Version: 5.6.20
-- PHP-Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Datenbank: `miguel`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `bier`
--

CREATE TABLE IF NOT EXISTS `bier` (
`id` int(11) NOT NULL,
  `name` varchar(100) CHARACTER SET latin1 NOT NULL,
  `groesse` double NOT NULL,
  `volumen` double NOT NULL,
  `bild` varchar(100) CHARACTER SET latin1 NOT NULL,
  `beschreibung` mediumtext CHARACTER SET latin1 NOT NULL,
  `herkunftsland` varchar(100) CHARACTER SET latin1 NOT NULL,
  `herkunftsort` varchar(100) CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_german2_ci AUTO_INCREMENT=465 ;

--
-- Daten für Tabelle `bier`
--

INSERT INTO `bier` (`id`, `name`, `groesse`, `volumen`, `bild`, `beschreibung`, `herkunftsland`, `herkunftsort`) VALUES
(100, 'JEVER', 50, 4, 'jever.jpg', 'Die Brauerei wurde 1848 gegründet. Etwas später wurde aus der Familienbrauerei\r\neine Grossbrauerei. Das Bier ist bekannt als leichtes, jedoch eines der hopfigsten Biere Deutschlands.\r\n\r\n', 'Deutschland', 'Niedersachsen'),
(101, 'ROTHAUS TANNENZÄPFLE ', 33, 5, 'rothaus_tannenzaepfle.jpg', 'Herb-bitter aber bekömmlich. Ein sehr schönes Pils aus dem Hochschwarzwald.\r\nEines der besten Biere Deutschlands. Bier des Jahrzehnts 1990-2000.\r\n', 'Deutschland', 'Grafenhausen'),
(102, 'RIEGELE COMMERZIENRAT ', 33, 5, 'riegele_commerzienrat.png', 'Für Kenner und Geniesser wahrer Braukunst. Harmonisch abgerundet im Malzaroma mit angenehmer Hopfenbitterkeit dank echter Symbiose von Körper (Malz) und Seele (Hopfen). ', 'Deutschland', 'Augsburg'),
(103, 'ANDECHSER HEFE WEISSBIER ', 50, 5, 'andechser_hefe_weissbier.jpg', 'Erst stechen markante Fruchtaromen wie Banane und Honigmelone hervor, dann folgen feine Gewürznelken. Sehr spritzig und erfrischend trinkt sich das Andechser Weissbier Hell und überzeugt mit einem vollen und weichen Körper. Im Abgang zeigt sich ein ausgewogenes Spiel einer leichten Honigsüße und einer eleganten  Säure mit einer hintergründigen Hopfenbitterkeit, die in einem harmonischen Abgang vergeht.', 'Deutschland', 'Andechs'),
(104, 'RAUCHBIER BAMBERG', 50, 5, 'rauchbier_bamberg.png', 'Dieses spezielle Bier ist charakterisiert durch seinen rauchigen Geschmack, welcher an geräucherten Schinken erinnert. Ein Getränk für Liebhaber des Rustikalen.', 'Deutschland', 'Bamberg'),
(105, 'CREW REPUBLIC 7:45 ESCALATION ', 33, 8, 'crew_republic_745_escalation.jpg', 'Ungefiltertes Double IPA, dass sich international mehr als messen kann! \r\nEin freches Charakterbier aus der deutschen Bierhauptstadt.', 'Deutschland', 'München'),
(106, 'WARSTEINER ALKOHOLFREI ', 33, 0, 'warsteiner_alkoholfrei.jpg', 'Das einzig wahre…. Aber ohne Alkohol.', 'Deutschland', 'Nordrhein-Westfalen'),
(107, 'T IJ IPA ', 33, 7, 't_ij_ipa.jpg', 'Diesem US-Punk-style IPA wird auch während des Reifeprozesses Hopfen beigefügt, um diese feinen Aromen von Grapefruit und Blüten zu erreichen. Ein Bier mit einem fruchtigen, bitteren Nachgeschmack, der für eine lange Zeit verweilt.', 'Niederlande', 'Amsterdam'),
(108, 'LA TRAPPE ISID’OR ', 33, 7, 'la_trappe_isidor.jpg', 'Das leicht süße, bernsteinfarbene Bier mit einem Hauch Karamell ist leicht herb im Geschmack und hat einen fruchtigen Abgang. La Trappe Isid’or wird mit Perle-Hopfen aus eigenem Anbau gebraut.', 'Niederlande', 'Tilburg'),
(109, 'CREW REPUBLIC MUNICH SUMMER ', 33, 4, 'crew_republic_munich_summer.jpg', 'Grillen an der Isar, relaxen am Gärtnerplatz, Sonne tanken im englischen Garten! So ist der Sommer in München und Munich Summer ist das Bier dazu! \r\nKompromisslos hopfig und erfrischend.\r\nDas Bekenntnis der Brauerei an die schönste Jahreszeit in der urigen Metropole Bayerns!\r\n', 'Deutschland', 'München	'),
(110, 'RIEGELE MICHAELI VON L. PIANA	 ', 75, 6, 'riegele_michaeli_von_l._piana.jpg', 'Das Riegele Michaeli von Louis Piana ist ein Märzen, das mit der Aromahopfensorte Cascade verfeinert wurde. Jede Flasche ist echte Handarbeit und streng limitiert. Seinen Namen verdank das Michaeli einer alten Tradition. Die bayrische Brauordnung aus dem Jahre 1516 legte fest, dass nur zwischen dem Tag des Hl. Michael (29. September) und dem Tag des Hl. Georg (23. April) gebraut werden durfte. Grund hierfür waren die heißen Sommertage und die damit einhergehende Brandgefahr. Um bis zur nächsten Brausaison Bier genießen zu können, wurde das Bier mit erhöhter Stammwürze und besonderer Hopfung eingebraut und mit Eisblöcken in den Bierkellern gekühlt. Für gewöhnlich konnte bis März frisches Eis geschlagen werden, woher sich auch der Name Märzen ableitet. \r\n\r\nEin fruchtiges Bouquet aus Litschi, Grapefruit und Mandarine verzaubert mit seinem Duft. Das Mundgefühl ist vollmundig und weich und überraschend frisch. Die perfekt eingebundene Kohlensäure unterstreicht den Genuss des Bieres. Die Fruchtnoten des Hopfens in Kombination mit angenehm dezenten Honig- Karamellnuancen, machen dieses Märzenbier zu einem wahren Schatz.\r\n', 'Deutschland', 'Augsburg'),
(200, 'Bel Pils', 25, 5.3, 'belpils.png', 'Bel ist ein helles Bier, wunderbar durstlöschend. Es ist leicht herb und feinhopfig, im echten "Premium-Stil". Aus dem Hause Moortgat (Duvel).', 'Belgien', 'Breendonk'),
(201, 'Vedett extra white', 33, 4.7, 'vedett_extra_white.jpg', 'Vedett hat einen köstlichen, überraschend erfrischenden Geschmack, mit einer an Orangen- und Zitronenzesten erinnernden Note, mit einem leicht bitteren Geschmack und trockenem Abgang. \r\nDas andere belgische Weissbier.\r\n', 'Belgien', 'Puurs'),
(202, 'wittekop', 33, 4.8, 'wittekop.png', 'Wittekop ist ein echtes belgisches Weissbier. Es ist unfiltriert, was ihm seine natürliche Trübe verleiht. Sein feines Aroma ist auf den Zusatz von Gewürzen (Koriander und Orangenschale) zurückzuführen und sein pikanter und fruchtiger Geschmack ist einem besonderen Gärungsverfahren zu verdanken.', 'Belgien', 'Puurs'),
(203, 'Martin''s pale ale', 33, 5.8, 'martins_pale_ale.jpg', 'Martin''s Pale Ale zeichnet sich durch einen intensiven Geschmack mit kräftigem Hopfenaroma aus. Es tritt in starken Kontrast zu den typisch belgischen Bieren.', 'Belgien', 'Genval'),
(204, 'Maredsous Blonde', 33, 6, 'maredsous_blonde.png', 'Maredsous ist ein echtes, natürliches Abteibier. Hell, malzig und fein gehopft. Nach alter Tradition der Zistenser Mönche gebraut.', 'Belgien', 'Puurs'),
(205, 'Orval blonde', 33, 6.2, 'orval_blonde.png', 'Orval hat keinen herben, aber doch kräftigen Biergeschmack – auf eine Art ein Mittelding zwischen fruchtig-süss und hopfig-bitter. Ein Bier für Liebhaber.', 'Belgien', 'Villers d''Orval'),
(206, 'Boon Oude Geuze', 37.5, 7, 'boon_oude_geuze.jpg', '"Brüsseler Champagner" – apartes Angebot aus Zitrusfrüchten und Melisse, im Hintergrund eine Nuance von Feuerstein. Im Mund sehr trocken trotz des Eindrucks von getrockneten Früchten und Brioche, fein moussierend.', 'Belgien', 'Lembeek'),
(207, 'Saison Dupont', 75, 6.5, 'saison_dupont.png', '"Brüsseler Champagner" – apartes Angebot aus Zitrusfrüchten und Melisse, im Hintergrund eine Nuance von Feuerstein. Im Mund sehr trocken trotz des Eindrucks von getrockneten Früchten und Brioche, fein moussierend.', 'Belgien', 'Tourpes'),
(208, 'Chimay premiere rouge', 75, 7.9, 'chimay_premiere_rouge.jpg', 'Das Bier hat einen cremigen Schaum und einen leichten Aprikosengeruch.\r\nEs wird am Besten bei 10-12° serviert, denn da erfährt man den vollen Geschmack und die volle Frische.\r\n', 'Belgien', 'Bovigny'),
(209, 'Lupus', 75, 7.5, 'lupulus.jpg', 'Lupulus ist ein helles Bier, mit einer Gärung in Champagnerflaschen und in Fässern. Die grossen Mengen Hopfen die während der Gärung zugefügt werden, bringen diesem goldenen Tropfen ein frisches Bouquet sondergleichen.', 'Belgien', 'Bovigny'),
(210, 'Hopus', 33, 8.5, 'hopus.jpg', 'Das ist ein helles Bier mit 5 verschiedenen, seltenen und starken Hopfen, die hier richtig dosiert sind. Alles  gibt ein Parfum und eine einzigartige Bitterkeit. Ein perfektes, ausgeglichenes Bier mit delikatem Malzgeschmack.', 'Belgien', 'Rebecq-Quenast'),
(211, 'Duvel Blonde', 33, 8.5, 'duvel_blonde.jpg', 'Duvel ist ein helles Bier, dessen Aussehen täuscht: unter seinem goldenen Gewand verbirgt es eine unvermutete Stärke und einen ausgeprägten Geschmack. Sein Schaum ist dick und cremig, sein Aroma ziemlich hopfig und seine Konsistenz füllig. Ein Teufelsbier! \r\n(Duvel bedeutet Teufel auf Flämisch).\r\n', 'Belgien', 'Breendonk'),
(212, 'Diabolici', 75, 8, 'diabolici.png', 'Ein teuflisches Bier, das wie der Name schon erahnen lässt, stark ist und durch seine 8% ein wärmendes Gefühl gibt. Hopfenbitterkeit und Malz sind in wohliger Harmonie.\r\n', 'Belgien', 'Genval'),
(213, 'Gulden Draak', 33, 10.5, 'gulden_draak.png', 'Gulden Draak ist ein belgisches Starkbier, das von der Brauerei Van Steenberge Ertvelde gebraut wird. Das süsse Bier hat bereits mehrere Preise gewonnen und passt ausgezeichnet als Digestif.\r\n', 'Belgien', 'Ertvelde'),
(214, 'ST-Feuillien triple', 33, 8.5, 'st-feullien_triple.jpg', 'Es hat ein reiches Aroma mit einzigartig kombiniertem, aromatischem Hopfen, Gewürzen und dem typischen Duft der Gärung; sehr fruchtig. Nachgärung in der Flasche, so entsteht ein aussergewöhnliches Aroma.', 'Belgien', 'Le Roeulx'),
(215, 'Westmalle Trappist tripel', 75, 9, 'westmalle_trappist_tripel.jpg', 'Westmalle Tripel ist von goldener Farbe. Ungefiltert ist eine leichte Trübung zu erkennen. Stark hopfiger und blumiger Geschmack, was zuweilen von einer Note Malz ausgeglichen wird. Vollmundig und kräftig vollendet der bittere Nachgeschmack diesen Biergenuss. \r\nWestmalle ist der Erfinder der Tripel-Biere.\r\n', 'Belgien', 'Malle'),
(217, 'Maredsous Tripel', 75, 10, 'maredsous_tripel.jpg', 'Die Säure, Süsse und Bitterkeit harmonieren bis zur Perfektion in Maredsous Tripel mit einem Alkoholgehalt von 10%. Ein bernsteinfarbenes Bier, der Geschmack rein, samtig und reich mit einem angenehmen Nachhall.', 'Belgien', 'Breendonk'),
(218, 'Rochefort 8°', 33, 8, 'rochefort.png', 'Vollmundig, dunkelbraun, ein intensiver Geschmack karamellisierten Malzes klar erkennbar; begleitet von fruchtigen, an Bananen erinnernde Aromen. Süss-bitterer Geschmack, gut ausgeglichen. ', 'Belgien', 'Rochefort'),
(219, 'Leffe vieille cuvée', 33, 8.1, 'leffe_vieille_cuvee.png', 'Leffe Vieille Cuvée hält eine langen, komplexen Geschmack, vereint mit der gemälzten Süsse, getönt durch geröstete Gerste und reifer Fruchtigkeit. Das Bier selbst ist vollmundig, ergibt ein cremiges Gefühl im Mund und hinterlässt ein häutiges Gefühl in Mund und Gaumen. Abgerundet wird das Geschmackserlebnis von kurzer Bitterkeit und dem wärmenden Alkoholgefühl.', 'Belgien', 'Dinant'),
(220, 'Liefmans fruitesse', 25, 4.2, 'liefmans_fruitesse.png', 'Liefmans Fruitesse ist eine frische und einzigartige Biermischung, die während 18 Monaten auf Kirschen lag. Diese Mazeration ist fein gemischt mit natürlichem Fruchtsaft aus Erdbeeren, Himbeeren, Kirschen, Heidelbeeren und Holunder. Das Resultat gibt ein fruchtiges Bier, leicht schäumend und mit einer angenehmen Süsse. Nicht nur für Damen geeignet.', 'Belgien', 'Oudenaarde'),
(221, 'Tripel Karmeliet', 33, 8, 'tripel_karmeliet.jpg', 'Ein süssliches Bier mit einem Hauch Vanille und Limette. \r\nEine komplexe belgische Spezialität mit Fülle.\r\n', 'Belgien', 'Buggenhout'),
(222, 'Cuvée des trolls', 25, 7, 'cuvee_des_trolls.jpg', 'Dieses goldenfarbene Blondbier hat eine leichte Orangennote, welche durch den Einsatz von trockenen Orangeschalen entsteht. Diese Note gibt dem Bier einen frischen, fruchtigen und sanften Geschmack.', 'Belgien', 'Pipaix'),
(223, 'La Chouffe blonde', 33, 8, 'la_chouffe_blonde.png', 'La Chouffe ist ein ungefiltertes, blondes und fruchtiges Bier mit leichtem Hopfengeschmack und einer feinen Koriandernote.', 'Belgien', 'Achouffe'),
(224, 'Kwak "Bière du chocher"', 33, 8.4, 'kwak_biere_du_cocher.jpg', 'Das historische Kutscherbier wird immer im originalen Kwak-Glas serviert und ist ein cremig-kräftiges Gebräu, dass von angenehmer Säure und Bitterkeit unterstützt wird.', 'Belgien', 'Buggenhout'),
(225, 'La Corne blonde', 33, 5.9, 'la_corne_blonde.jpg', 'Obergäriges großes bitteres belgisches Bier mit einer Idee von Zitrusfrüchten im typischen Horn serviert.', 'Belgien', 'Ebly'),
(226, 'Averbode Abteibier', 33, 7.5, 'averbode_abteibier.jpg', 'Sehr prickelndes Strong Ale mit Noten von Zitrusfrüchten und Heu. Schöne Harmonie von Malzsüsse und Bitterkeit vom Hopfen eingebunden in ungeahnter Frische. Im Abhang sind Säure und Hefebetont.', 'Belgien', 'Averbode'),
(227, 'Bush de Nuits', 75, 13, 'bush_de_nuits.jpg', 'Älteste und authentischste Brauerei der Wallonie, 100% unabhängig. Herstellung völlig natürlicher Biere, lehnt Herstellung von Standardbieren, welche nur anders etikettiert werden, ab. \r\nDer gesamte Brauprozess erfolgt im Haus. \r\nDas Bush de Nuits reift nach traditioneller Methode in Eichenfässern, welche zuvor für den weltbekannten Burgunderwein Nuits Saints-Georges verwendet wurden. Es ist ein schmackhaftes Bier mit weinähnlichen Aromen von roten Früchten und bringt erstaunliche, harmonische Geschmacksnuancen hervor. Das Bush de Nuits ist nicht gefiltert und durchläuft keiner Nachgärung innerhalb der Flasche.\r\n', 'Belgien', 'Pipaix'),
(228, 'La chouffe blonde', 75, 8, 'la_chouffe_blonde2.jpg', 'Die Geschichte der Brasserie d’Achouffe ist wie ein Märchen; "ein Hobby das zum Beruf wurde“, scherzen die Gründer Chris Bauweraerts und Pierre Gobron. Die beiden Freunde haben im Jahre 1982 mit dem Brauen in dem kleinen Dorf Achouffe in den belgischen Ardennen angefangen. Angelehnt an die heimischen Legenden, wurde ein Zwerg zum Logo der Brauerei gewählt.\r\n\r\nLa Chouffe ist ein ungefiltertes blondes Bier, das sowohl in der Flasche als auch in Fässern nachgärt. Es ist angenehm fruchtig, mit Koriander gewürzt und vom Hopfen gefärbt.\r\n', 'Belgien', 'Achouffe'),
(229, 'Houblon Chouffe', 33, 9, 'houblon_chouffe.png', 'Dieses sehr hopfige Bier enthält in der Tat dreimal mehr Hopfen als La Chouffe. Das Bier bietet ein harmonisches Gleichgewicht zwischen einer markanten Bitterkeit und einem angenehm fruchtigen Geschmack. Der hohe Alkoholhegalt gleicht den Biergeschmack aus.', 'Belgien', 'Achouffe'),
(230, 'Nogne Global Pale ale', 50, 4.5, 'nogne_global_pale_ale.jpg', 'Ein Meisterstück mit 13 Hopfensorten aus aller Welt. Sehr komplex und wunderbar hopfig – \r\nversteht sich von selbst. Dieses Bier ist wahrlich ein Erlebnis für sich. \r\n', 'Norwegen', 'Grimstad'),
(231, 'Nogne #500', 50, 10, 'nogne.jpg', 'Wenn Nøgne Ø beschlossen, ihre 500. Partie als Jubiläumsbier zu brauen, war schnell klar, dass die wichtigsten Zahlen 5 Malze, 5 Hopfen, 10% Alkohol und 100 IBUs sein werden. Das Ergebnis ist ein unglaublich reiches und königlich hopfiges IPA. Malzig genug, um fast ein Gerstenwein zu sein.', 'Norwegen', 'Grimstad'),
(301, 'TROOPER / IRON MAIDEN ', 50, 4.7, 'trooper.jpg', 'Die Hard Rock-Band Iron Maiden und die Robinsons Brauerei haben ein rötlich-helles Bier entwickelt. Hopfen und Malz sind die Hauptaromen dieses Bieres, es bleibt jedoch dank seiner guten Ausgewogenheit „süffig“. Man kann außerdem eine leichte Säure und einen feine Zitronennote feststellen', 'England', 'Stockport'),
(302, '\r\nHOLY GRAIL BY MONTHY PYTHON’S \r\n', 50, 4.7, 'holy.jpg', 'Dieses rotblonde Premium Bitter ist leicht trüb, offenbart eine zarte Süsse und Fruchtigkeit und beginnt elegant malzig bevor im Nachhall der Hopfen überwiegt.', 'England', 'North Yorkshire'),
(303, 'ST. AUSTELL PROPER JOB ', 50, 5.5, 'staustell.jpg', 'Ein authentisches, mit Quellwasser aus Cornwall gebrautes IPA. Erfrischend, eher leicht, aber sehr komplex und harmonisch.', 'England', 'Cornwall'),
(304, 'SPITFIRE ', 50, 4.5, 'spitfire.jpg', 'Dieses Premium Kentish Ale hat durch das würzige Malz wunderbare Aromen von Rosinen und süßen Orangen. Abgerundet wird dieses Erlebnis mit dem intensiven Hopfengeschmack.', 'England', 'Faversham'),
(305, 'BOMBARDIER PREMIUM BITTER ', 50, 5.2, 'bombardier.jpg', 'Ein « Bitter Ale » - obergärig, kupferfarbig, Aromen von Pfeffer-Hopfen und Trauben, mit fruchtigem Schwarzbeerengeschmack, saftiges Malz, mit starkem und pikanten Hopfen.', 'England', 'Bedford'),
(306, 'BISHOPS FINGER ', 50, 5.4, 'bishops.jpg', 'Ein starkes Ale mit bitterem Geschmack und einer Note gerösteten Malzes. Very Britisch!', 'England', 'Faversham'),
(307, 'SHEPHERD NEAME DOUBLE STOUT ', 50, 5.2, 'shepherd.jpg', 'Dieses herrliche Beispiel für ein klassisches Doppel-Stout liefert einen samtig-glatten, trockenen Gaumen, verbrannte Aromen - ergänzt durch Braten-, Kakao- und Kaffeenoten. Schwarz, cremig und lecker; es ist ein Shepherd Neame Meisterwerk.', 'England', 'Faversham'),
(308, 'SUPER BOCK LAGER ', 33, 5.2, 'super.jpg', 'Das Nr. 1 Bier in Portugal ist leicht bitter und ein typisches Lagerbier.', 'Portugal', 'Leca do Balio'),
(309, 'SUPER BOCK DUNKEL ', 33, 5, 'super2.jpg', 'Super Bock Dunkel ist ein schwarzes Bier, welches leicht fruchtig und mild ist, mit einem  leichten Karamellaroma.', 'Portugal', 'Leca do Balio'),
(310, 'GUINNESS DRAUGHT ', 44, 4.2, 'guinness.jpg', 'Das bekannte, dunkle Bier aus Irland ist besonders beliebt aufgrund seines cremigen Schaumes und seiner Bitterkeit. Entweder man liebt es oder nicht.', 'Irland', 'Dublin'),
(311, 'MAGNERS ORIGINAL CIDER ', 56.8, 4.5, 'magner.jpg', 'Apfelweinhaltiges Getränk mit 66% Apfelwein. Erfrischender, irischer Cider. Auf Eis serviert!', 'Irland', 'Clonmel'),
(312, 'DEAD PONY CLUB ', 33, 3.8, 'dead.jpg', 'Californien Pale Ale mit Noten von Lychee und Grapefruit, sehr erfrischend, leicht und doch mundfüllend. Trotz des Namens sehr belebend.', 'Schottland', 'Fraserburgh'),
(313, 'PUNK IPA ', 33, 5.6, 'punk.jpg', 'Punk Indian Pale Ale der schottischen Brewdog Brauerei zeichnet sich vor allem durch seine angenehm tropisch fruchtigen Noten aus. IPA–typisch ist der Geschmack sehr hopfengeprägt. ', 'Schottland', 'Fraserburgh'),
(314, 'RUSSIAN IMPERIAL STOUT ', 66, 9.5, 'russianimperial.jpg', 'Mit diesem dunklen Russian Imperial Stout ehrt Brewdog die Geschichte dieses Bierstils. Geschmacklich wird das Bier von Schokoladen und Kaffeenoten dominiert. ', 'Schottland', 'Fraserburgh'),
(315, 'ST. PETER’s INDIA PALE ALE  		   ', 50, 5.5, 'stpeter.jpg', 'Eine traditionelle und authentische Interpretation dieses antiken Stils des klassischen Bieres. Es gewann mehrere Preise im Vereinigten Königreich einschließlich des 1.Platzes unter den Flaschenbieren, der ihm von einer nationalen Tageszeitung verliehen wurde. \r\n\r\nDer Geschmack ist nussig und vordergründig hopfig mit leichter Frucht und dezenter Malzsüsse.\r\n', 'England', 'Suffolk'),
(316, 'Beimiguel Spezial Lager', 50, 4.8, 'Beimiguel_Spezial_Lager.jpg', 'Helles Lager-Bier, ungefiltert, aus Pilsner Malz und Hopfen, mit untergäriger Hefe vergoren.', 'Schweiz', 'Hünenberg'),
(317, 'Luzerner Original', 50, 5, 'Luzerner_Original.jpg', 'Das Echte. Gebraut in der Stadt Luzern. Spezialbier, das eine Stammwürze von 12% aufweist und mit einer Mischung aus vier verschiedenen Malzen eingebraut wird. Durch die lange Lagerung erhält es einen vollmundigen Charakter.', 'Schweiz', 'Luzern'),
(318, 'Luzerner Weizen', 50, 5.2, 'Luzerner_Weizen.jpg', 'Ein wunderbar frisches Weizenbier, das etwas dunkler eingebraut wird als traditionelle Hefeweizen. Unser ', 'Schweiz', 'Luzern'),
(319, 'Eichhof Lager', 58, 4.8, 'Eichhof_Lager.jpg', 'Das goldgelbe, helle, milde Lager überzeugt durch seine Frische und durch die leichte, malzige Aromatik. Eichhof Lager verkörpert Heimat, Tradition und Geselligkeit und ist bei vielen Konsumenten sehr beliebt.', 'Schweiz', 'Luzern'),
(320, 'Rousse Du Mont Blanc', 75, 7.2, 'Rousse_du_Mont_Blanc.jpg', 'Das Bier ist kastanienrot und schön anzusehen, es duftet leicht süsslich karamellartig. Das Aroma ist fein süsslich, mit leichten Mandelnoten und einer gewissen Röstmalznote. Es ist sehr mild und sehr süffig, auch der Nachgeschmack bleibt mild und wird nur zum Ende ganz leicht alkoholisch.', 'Frankreich', 'Les Houches'),
(321, 'Eichhof Klosterbräu', 50, 4.8, 'Eichhof_Klosterbraeu.jpg', 'Klosterbräu Edeltrüb ist gelbbraun, geschmeidig bitter, unfiltriert und deshalb trüb. Die angenehme Hefenote sowie die Milde und Süffigkeit runden das Geschmackserlebnis ab.', 'Schweiz', 'Luzern'),
(322, 'CORONA', 33, 4.6, 'Corona.jpg', 'Corona Extra hat neben Hopfen auch Mais und Reis unter seinen Zutaten und gehört daher zu den Maisbieren. Das bekannteste Bier von Mexiko mit einem milden Geschmack.', 'Mexiko', 'Guadalajara'),
(323, 'SIERRA NEVADA PALE ALE', 35, 5.6, 'Sierra_Nevada_Pale_Ale.jpg', 'Der premium Cascade-Hopfen verleiht dem Pale Ale seinen unverwechselbaren würzigen Geschmack und ein langanhaltendes Bouquet. Ein Kunststück aus Übersee.', 'USA', 'Chico, CA'),
(324, 'SIERRA NEVADA STOUT', 35, 5.8, 'Sierra_Nevada_Stout.jpg', 'Ein cremiges und malziges Bier mit einem Hauch Karamell, welches ihm zusammen mit dem Malz die kennzeichnende schwarze Farbe verleiht.', 'USA', 'Chico, CA'),
(325, 'MAUDITE', 34, 8, 'Maudite.jpg', 'Ein rotfarbiges Starkbier, mit einem leicht fruchtigen Geschmack und feinem Hopfenaroma.\r\nMaudite stammt aus einer erstklassigen kanadischen Brauerei, die ausschliesslich Höchstqualitätprodukte herstellt.', 'Kanada', 'Chambly'),
(326, 'BROOKLYN LAGER', 35, 5.2, 'Brooklyn_Lager.jpg', 'Dieses Bier widerspiegelt wahrhaft Malz und Hopfen. Der Geschmack kommt von der Technik "dry hopping", eine uralte Praxis; das Bier wird mit frischem Hopfen versetzt, um einem langen Reifeprozess durchlaufen zu können.', 'USA', 'Brooklyn, NY'),
(400, 'BUDWEISER BUDVAR ', 33, 5, 'budweiser.jpg', 'Die Popularität dieses Bieres beruht auf seiner 700 jährigen Brautradition und der fein gehopften Frische dieses aussergewöhnlichen Bieres. Es besitzt einen süsslichen, milden und malzigen Geschmack. ', 'Tschechien', 'Ceske Budejovice (Budweis)'),
(410, 'BERNARD AMBER LAGER ', 50, 4.7, 'bernard.jpg', 'Halbdunkles nicht pasteurisiertes Lagerbier mit Zugabe von frischer Hefe.', 'Tschechien', 'Humpolec'),
(411, 'COOPERS ORIGINAL PALE ALE', 37.5, 4.5, 'coopers.jpg', 'Der fruchtige und starke Geschmack des Coopers hat eine neue Generation von Pale Ale Trinkern           in Australien hervorgebracht.', 'Australien', 'Regency Park'),
(412, 'QUILMES', 35, 4.9, 'quilmes.jpg', 'Probieren Sie Quilmes mit seinem frischen, nicht zu herben Geschmack. \r\nMillionen von Argentiniern können nicht irren!\r\n', 'Argentinien', 'Buenos Aires'),
(413, 'AFFLIGEM BLONDE ', 33, 6.8, 'affligem.jpg', 'Sechs Ritter tauschten ihre Rüstungen gegen schlichte Mönchskutten und gründeten im Jahr 1074 im Herzen von Belgien die Abtei von Affligem. Seit jener Zeit wird dort ein Bier gebraut, bis heute unverändert in der Rezeptur. Es zählt zu den ältesten von nur 22 Abteibieren weltweit. Was es aber so ganz besonders macht, ist die zweite Gärungsphase - direkt in der Flasche.\n\nAffligem Blonde ist eine leuchtend-goldgelbe Spezialität. Geruch nach frischem Brot, Zitrusfrüchten und einem Hauch Vanille. Im Geschmack feine Nuancen von Marzipan und Mandel, mit einer leichten Bitterkeit im Abgang.\n', 'Belgien', 'Opwijk'),
(414, 'LA CORNE TRIPLE', 33, 10, 'corne.jpg', 'Das La Triple Corne du Bois des Pendus ist ein kräftiges Bier mit hervorragendem Geschmack und einem hellen Kupferton. Anders als seine Schwester mit 5,9% Vol. ist es bitterer und richtig blumig.\r\nDas Bier ist sehr duftig und überraschend leicht trinkbar - wahrlich eine angenehme Entdeckung. Sie werden sich wundern: es enthält weder Zucker noch Gewürze. \r\n', 'Belgien', 'Ebly'),
(415, 'CUVÉE DU CHÂTEAU ', 33, 11, 'cuvee.jpg', 'Der Geschmack des Cuvée du Château trägt die klare Handschrift von der Brauerei Kasteel. Vergleichbar mit dem an Portwein erinnernden Kasteel Donker, jedoch mehr in Richtung Madeira. Dieses ‘premier cru classé’ ist im Quadrupel. Dieser starke, dunkelbraune Biertyp bewegt sich zwischen Süsse und Bitterkeit mit Röstaromen und karamelligem Malz, das im Finish von der Herbe des Hopfens abgelöst wird.', 'Belgien', 'KASTEEL, Ingelmunster	'),
(416, 'LINDEMANS FRAMBOISE ', 25, 2.5, 'lindemans.jpg', 'Die Brauerei Lindemans genießt in der Bierwelt seit 200 Jahren einen hervorragenden Ruf. Lindemans braut traditionelle und gesüßte Lambic-Sorten nach der Braukunst der Spontangärung. Die Brauerei verwendet dazu nur die besten Zutaten.\r\nLindemans Framboise ist herrliches Saisonbier auf Lambic-Basis, mit 30 % reinem Himbeersaft.\r\n', 'Belgien', 'Vlezenbeek'),
(417, 'SCOTCH DE SILLY ', 33, 8, 'scotch.jpg', 'Im letzten Jahrhundert brauten die großen Farmen von Hainaut die Gerste und den Hopfen. Silly, ein Dorf im Dreieck von Ath, Enghien und Soignies, gelegen an der Sylle, die ihm seinen Namen verleiht, gründete 1950 eine Brauerei, ursprünglich mit Namen "Cense de la Tour".\r\n\r\nSein Geschmack ist bemerkenswert, leicht und harmonisch komponiert. Es zeigen sich feine Düfte, die an Holz und Haselnuss erinnern und eine herrliche Frische am Gaumen, begleitet von dezenter und doch körperreicher Hopfenbitterkeit.\r\n', 'Belgien', 'Silly'),
(418, 'SCOTCH SILLY COGNAC ', 75, 11, 'scotch_silly.jpg', 'Das Scotch Silly Barrel Aged Bier wird nach dem Brauen für sechs Monate in ein altes Cognacfass gegeben, um dort auszureifen. Danach wird es nur in 75cl Flaschen abgefüllt.\r\n\r\nDieses Scotch Ale offenbart schon in der Nase dunkles Malz, welches auch im Mund den Takt vorgibt. Die delikaten, traubigen Noten des Cognac stützen die Karamellsüsse dieser Rarität - es existieren weltweit nur 13''000 Flaschen.\r\n', 'Belgien', 'BARREL AGED, Silly'),
(419, 'LUPULUS HIBERNATUS ', 75, 9, 'lupulus.jpg', 'Lupulus Hibernatus ist ein beinahe schwarzes Gebräu mit gemalzter Pilsener und gerösteter Gerste. Neben slowenischem Hopfen wird noch ein Hauch Zimt beigefügt. Der kräftige Körper wird gleichermassen von Süsse und Bitterkeit getragen und endet mit zarten Kaffeenoten. Ein wahres Winterbier!', 'Belgien', 'Bovigny'),
(420, '\r\nCUVÉE VAN DE KEIZER ROOD \r\n', 75, 10, 'cuvee_keizer.jpg', 'Mit authentischen und einzigartigen Aromen schafft es das Bier zu einem internationalen Ruf, gekrönt durch zahlreiche Auszeichnungen. Die alten Rezepte sind immer noch die Grundlage des Brauprozesses.\r\nDie würzige Nase wird von feinen Hefearomen unterstrichen. Am Gaumen beginnt es trocken, gefolgt von einem blumigen Charakter, der von einer ausgezeichneten Malzsüsse und einer feinen Bitterkeit unterstützt wird. Am Ende ist eine feine Alkoholwärme zu vernehmen.\r\n', 'Belgien', 'GOUDEN CAROLUS, Mechelen'),
(421, 'GOUDEN CAROLUS, Mechelen', 75, 11.5, 'carlos.jpg', 'Dieses Schaumweinbier wird in Belgien gebraut und anschließend in Frankreich unter Zugabe von Schaumwein-Hefe mehrere Monate gereift.\r\nDieses Bier zeigt vielschichtige Aromen und ist ein Geschenk des Himmels (lat. Deus = Gott). In der Nase zeigen sich Noten von Minze, frischem Apfel, Hopfen und Ingwer. Komplex und delikat ist der Geschmack des Bieres. Zwar nimmt man auf der Zunge ein leichtes Kribbeln wahr, aber dennoch erscheint das Deus angenehm weich und überrascht mit dem Aroma von Äpfeln, reifen Trauben und weiteren fruchtigen Aromen. In seinem Abschluss ist das Sekt Bier wunderbar trocken.\r\n', 'Belgien', 'Buggenhout'),
(422, 'CAULIER EXTRA ', 33, 4.3, 'caulier_extra.jpg', 'Leichtes Bier ohne Zucker mit reichen Aromen von Zitrusfrüchten. Für Diabetiker und Zöliakie-Betroffene geeignet. Dank seiner niedrigen glykämischen Last und wenigen Kalorien ist Caulier Extra das ideale alkoholische Getränk für ein gutes Gewissen für diejenigen, die Diät oder ihren Blutzuckerspiegel niedrig halten müssen – den anderen schaden die positiven Effekte auch nicht!', 'Belgien', 'Ghislenghien'),
(423, '\r\nLIEFMANS GOUDENBAND \r\n', 75, 8, 'liefmans.jpg', 'Ursprünglich hieß dieses Bier IJzerenband (Eisenband), als Verweis auf die Eisenreifen um die Bierfässer – den Champagnerkorken erhielt es mit dem neuen Namen Goudenband(Goldband). Das Bier wird in offenen Gärbottichen gelagert, wo eine gemischte bzw. spontane Gärung stattfindet. Die Hopfengabe erfolgt mit Herkules Hopfen. Anschliessend kommt es zur Reifung 4 bis 12 Monate in den Keller. Dem fertig gereiften Bier wird anschließend Jungbier zugegeben, so dass eine weitere Gärung in der Flasche beginnt, deren Erkennungszeichen das von Hand umwickelte Papier ist.\r\nTrocken, leichte malzige Karamellnoten, nussig, angenehme Frucht und Sultaninen, belebt von der Bitterkeit des Herkules-Hopfens.\r\n', 'Belgien', 'Oudenaarde'),
(424, 'DELIRIUM TREMENS ', 33, 8.5, '1.jpg', 'Seine Authentizität beruht auf seinen 3 verschiedenen Hefesorten sowie auf seiner ganz besonderen und originellen Verpackung, die an das Tongeschirr aus Köln erinnert und einige schräge Details aufweist:  Rosa Elefanten, stolzierende Krokodile und ein Drache. Die Schriftart in der „Delirium Tremens“ (lat. Alkoholdilirium) geschrieben ist, passt mit ihren Schnörkeln gut zum Namen. Eine hellblaue Aluhalskrause setzt dem Ganzen die Krone auf. Hoher Wiedererkennungswert!\r\nWen wundert es, dass man bei einem Bier mit 8,5% Vol. gewisse Alkoholaromen schmeckt. Diese sind eher stark ausgeprägt und kommen delikat mostig zum Vorschein. Hintergründig erkennt man ein vielschichtiges und harmonisches Spiel von Malz, Frucht und Bitterkeit. \r\n', 'Belgien', 'Melle'),
(425, 'ST FEUILLIEN TRIPLE ', 75, 8.5, 'le_roulex.jpg', 'Die Brauerei geht auf den gleichnamigen irischen Mönch zurück, der im Jahr 655 in Roeulx enthauptet wurde. Zu seinem Gedenken errichteten seine Anhänger an gleicher Stelle eine Kapelle - die spätere Abtei Saint-Feuillien du Rœulx, wo schon seinerzeit Bier gebraut wurde. \r\n1873 belebte die Familie Friart die Brauereitradition neu und zelebriert heute bereits in 4. Generation authentische belgische Brauereikunst.\r\nDas Erfolgsrezept von Saint-Feuillien: Die obergärigen Biere werden ohne Zusatzstoffe nach alten überlieferten Braumethoden gebraut: Verwendet werden hochwertiger aromatischer Hopfen und ausgewähltes Malz. Die einmonatige horizontale Lagerung sowie eine mindestens zweiwöchige zweite Flaschengärung sind das Geheimnis des St Feuillien, das es als Blonde, Brune Réserve, Triple, Cuvée de Noël, Saison, Grand Cru, Grisette Blonde, Blanche, Waldfrucht- und Kirsch-Bier gibt, die am besten in dem typisch bauchigem Glas genossen werden.\r\n', 'Belgien', 'Le Roeulx'),
(426, '\r\nDas Bier St-Feuillien Triple\r\n', 0, 0, 'das_bier.png', 'hat ein weisses, glattes und sehr kompaktes Bouquet. Seine blass-gelbe Farbe ist sehr charakteristisch und enthüllt eine unverwechselbare Malzigkeit. Es hat ein reiches Aroma mit einer einzigartigen Kombination von aromatischem Hopfen, Gewürzen und dem typischen Duft der Gärung - sehr fruchtig. Durch die stark obergärige Hefe entwickelt das Bier bei der Nachgärung in der Flasche ein unvergleichliches Aroma.\r\nSt Feuillien Triple hat einen sehr starken und außergewöhnlich lang anhaltenden Geschmack, dies verdankt es seiner Dichte und seiner langen Lagerzeit. \r\nOb als erfrischender Aperitif  im Sommer oder aber auch im Winter vor dem Kamin serviert ist es immer ein Genuss.\r\n', 'Belgien', ' St. Feuillien'),
(427, 'BERTINCHAMPS BLONDE ', 50, 6.2, 'bertinchamps_blonde.png', 'Eine blumige Nase nach frischem Heu, Aromen von geröstetem Getreide mit einem Hauch von Pfeffer. Gut balanciert mit angenehmer Bitterkeit am Ende. \r\n\r\nEin erfrischendes Bier zum Geniessen.\r\n', 'Belgien', 'Gembloux'),
(428, 'CAULIER EXTRA ', 33, 4.3, 'caulier_extra.jpg', '\r\nLeichtes Bier ohne Zucker mit reichen Aromen von Zitrus. \r\nFür Diabetiker und Zöliakie-Betroffene geeignet.\r\n\r\nDank seiner niedrigen glykämischen Last und wenigen Kalorien ist Caulier Extra das ideale alkoholische Getränk für ein gutes Gewissen für diejenigen, die Diät halten oder ihren Blutzuckerspiegel niedrig halten müssen – allen anderen schaden die positiven Effekte auch nicht!\r\n', 'Belgien', 'Ghislenghien'),
(429, '\r\nAVERBODE ABTEIBIER \r\n', 33, 7.5, 'averbode.png', '\r\nSehr prickelndes Strong Ale mit Noten von Zitrusfrüchten und Heu. Schöne Harmonie von Malzsüsse und Bitterkeit vom Hopfen eingebunden in ungeahnter Frische. Im Abhang sind Säure und Hefe betont.\r\n', 'Belgien', 'Averbode'),
(430, 'LISBETH ', 75, 7.5, 'lisbeth.png', 'Lisbeth Officina Della Birra ist ein helles Indian Pale Ale aus obergäriger Hefe mit 7.5% Vol. Officina Della Birra ist eine Schweizer Brauerei, welche unpasteurisierte Biere produziert. Sie erkunden dabei eine Vielzahl von Biertypen und nutzen lokale Zutaten wie "Farina Bona della Val Onsernone", Tessiner Kastanienhonig oder die hierzulande beliebte Traubensorte "Americana". \r\n\r\nLisbeth ist die Hauptfigur in der „Millenium Trilogie“ von Stieg Larsson. Sie ist genial, intelligent und alternativ. Genau wie dieses Bier. Exotischer Charakter; Grapefruit, Litschi und Passionsfrucht.\r\n', 'Schweiz', 'Bioggio'),
(431, 'QUÖLLFRISCH HELL', 33, 4.8, 'quoellfrisch_hell.png', 'Das Bier zeichnet sich durch seine Milde und leichte Fruchtigkeit aus. Gebraut wird es aus reinem Pilsenermalz und drei verschiedenen Hopfensorten aus Stammheim und der Hallertau. Die bis zu 3 Monate lange Lagerung in dem Felsenkeller gibt dem Bier seine Ausgewogenheit.', 'Schweiz', 'Appenzell'),
(432, 'WENDELINUS INTENSIA ', 33, 9, 'WENDELINUS_INTENSIA.JPG ', 'Gestützt auf eine mehr als vierhundertjährige Geschichte, ist die Brauerei METEOR die älteste noch aktive Frankreichs. Nur wenige Kilometer von Straßburg gelegen, befindet sie sich seit 1640 zu 100% in unabhängigem Familienbesitz.\r\nGebraut nach der Tradition der Mönche von Wissembourg, die hier begannen, ist das Wendelinus das Resultat von jahrhundertealtem Wissen.\r\nDieses intensive Gebräu zeigt Bernstein- und Goldreflexe im Glas und eine cremige Textur am Gaumen, die anfangs ihre Frucht offenbart, die sogleich von malziger Fülle unterstützt wird.\r\n', 'Frankreich', 'Hochfelden'),
(433, 'CLOS NORMAND BRUT CIDRE BOUCHÉ', 75, 4, 'CLOS_NORMAND_BRUT_CIDRE_BOUCHE.jpg', 'Clos Normand Brut entsteht in den Obstgärten der Normandie. Klar, dunkel golden und eine feine Perlage, die rasch nach oben steigt, beschreiben die Erscheinung dieses Apfelciders. Erstaunliche Nuancen von Bratapfel und Apple Pie sind zu erkennen – eine harmonische Kombination auch von frischem Apfel und Rohrzucker. Die Süsse ist zwar nicht vordergründig, aber eine klare Komponente in diesem hervorragenden Getränk. ', 'Frankreich', 'Issy-Les-Moulineaux'),
(434, 'PIETRA DE NOËL ', 75, 7, 'PIETRA_DE_NOEL.jpg', 'Gebraut für die Advent- und Weihnachtszeit und aus der letzten Gerstenernte, die im Jahr gemalzt wird, begleitet Pietra de Noël den Kenner längst schon das ganze Jahr über. Intensive Aromen, dominiert von korsischen Edelkastanien kennzeichnen dieses etwas andere Bier.', 'Frankreich', 'Korsika'),
(435, 'SOL', 33, 4.5, 'SOL.png', 'Das mexikanische Bier, wird seit 1899 gebraut.\r\nEs verkörpert den Espiritu Libre – den freien Geist.\r\n\r\nNach Hunderten von Jahren dickflüssigen spanischen Biers brachte ein revolutionärer deutscher Braumeister den Mexikanern ein leichtes, erfrischendes Bier, «El Sol», aus dem später «Sol» wurde..\r\n', 'Mexiko', 'Veracruz-Llave'),
(437, 'ST. PETER’s INDIA PALE ALE  	', 50, 5.5, 'stpeter.jpg', 'Eine traditionelle und authentische Interpretation dieses antiken Stils des klassischen Bieres. Es gewann mehrere Preise im Vereinigten Königreich einschließlich des 1.Platzes unter den Flaschenbieren, der ihm von einer nationalen Tageszeitung verliehen wurde. \r\n\r\nDer Geschmack ist nussig und vordergründig hopfig mit leichter Frucht und dezenter Malzsüsse.\r\n', 'England', 'Suffolk'),
(438, 'AMARCORD AMA BIONDA ', 35, 6, 'AMARCORD_AMA_BIONDA.jpg', 'Ein typisch mediterranes, hochqualitatives Bier, das die Geschmacksvielfalt Italiens widerspiegelt. Ein frisches und leichtes Getränk zum Geniessen.\r\n \r\n', 'Italien', 'Apecchio'),
(439, 'BENNO STIFT ENGELSZELL ', 33, 6.9, 'BENNO_STIFT_ENGELSZELL.png', 'Rot-gelbes Trappistenbier mit würzig-grasigem elsässischen Hopfen, getragen von angenehmen Malzaromen. Feine karamellige Süsse.\r\n', 'Oesterreich', 'Engelhartszell'),
(440, 'SAN MIGUEL ', 33, 5.4, 'SAN_MIGUEL.jpg', 'Das beliebteste Bier Spaniens mit der perfekten Balance zwischen Milde und Bitterkeit.', 'Spanien', 'Barcelona'),
(441, 'IMPERIAL NESSIE ALE ', 75, 8.7, 'IMPERIAL_NESSIE_ALE.png', 'Ein dunkel bernsteinfarbenes Scotch Ale, gebraut mit 6 verschiedenen Malzen. Nessie gibt Dir ein wohliges Wärmegefühl und überzeugt mit üppiger Malzsüsse, die durch eine subtile Hopfenbitterkeit getragen wird.', 'Oesterreich', 'St. Martin              '),
(442, 'GUSSWERK DIES IRAE ', 50, 10.9, 'GUSSWERK_DIES_IRAE.jpg', 'Nur wenige Biere sprechen heute den Biertrinker mit Latein an. Für ein Erinnerungsbier an Mozarts Tod und sein unvollendetes Requiem aus dem Jahr 1791 scheint es angemessen - ebenso wie die ehrenvolle Aufmachung in der schwarzen Steingutflasche mit Bügelverschluss. Es ist ein handwerklich gebrautes extra Starkbier des Bierstils "Barley Wine". \r\n\r\nIn den Geruch nach dunklen Malztönen stimmen Zartbitterschokolade, Kaffee und Schwarzbrot mit ein. Beim Trinken wird durch süßes Röstmalz, wärmenden Alkohol und Hopfenbittere eine imposante Grundstimmung mit komplexer Aromatik erzeugt. Eine wunderbare vollendete Braukomposition von Reinhold Barta. \r\n\r\nFruchtig im Antrunk, unterlegt von feinen Bittermandeln, kommt der Genuss gewaltig auf die Zunge. Töne von Grapefruit mischen sich harmonisch in den elegant-kräftigen Körper. \r\n', 'Oesterreich', 'Salzburg'),
(443, 'BUDWEISER BUDVAR ', 33, 5, 'BUDWEISER_BUDVAR.jpg', 'Die Popularität dieses Bieres beruht auf seiner 700 jährigen Brautradition und der fein gehopften Frische dieses aussergewöhnlichen Bieres. Es besitzt einen süsslichen, milden und malzigen Geschmack. ', 'Tschechien', 'Ceske Budejovice (Budweis)'),
(444, 'BERNARD AMBER LAGER ', 50, 4.7, 'BERNARD_AMBER_LAGER.jpg', 'Halbdunkles nicht pasteurisiertes Lagerbier mit Zugabe von frischer Hefe.', 'Tschechien', 'Humpolec'),
(446, 'DEUS BRUT DES FLANDRES', 75, 11.5, 'DEUS_BRUT_DES_FLANDRES.png', 'Dieses Schaumweinbier wird in Belgien gebraut und Geschenk des Himmels (lat. Deus = Gott). In der Nase anschließend in Frankreich unter Zugabe von Schaumwein-Hefe mehrere Monate gereift.\r\nDieses Bier zeigt vielschichtige Aromen und ist ein zeigen sich Noten von Minze, frischem Apfel, Hopfen und Ingwer. Komplex und delikat ist der Geschmack des Bieres. Zwar nimmt man auf der Zunge ein leichtes Kribbeln wahr, aber dennoch erscheint das Deus angenehm weich und überrascht mit dem Aroma von Äpfeln, reifen Trauben und weiteren fruchtigen Aromen. In seinem Abschluss ist das Sekt Bier wunderbar trocken.\r\n', 'Belgien', 'Buggenhout'),
(447, 'BERTINCHAMPS', 0, 0, 'bertinchamps.png', '„B“ steht stolz in der Mitte des Logos und lädt zum Fantasieren ein: Bertichamps, Beer, Belgium, Benoit…\r\nDie Familie Humblet suchte ein Anwesen, um eine neue Brauerei aufzubauen und gleichzeitig ihre Tradition mit einer langen Liste von Bieren, gebraut von Vater Benoit Humblet, fortzuführen.\r\n2011 wurde man mit dem Hof von Bertinchamps, unweit von Gembloux, fündig. Wohlgleich steinalt und teilweise verfallen, war der Charakter des Hofes atemberaubend. Im März 2013 konnte nach intensiver Restaurierung die Brauerei in der alten Scheune in Betrieb genommen werden. Hochmoderne Gärtanks mit einer Kapazität von 6000 hl verschmelzen mit ehrwürdigen Elementen von vor 700 Jahren. Hier entstehen wieder traditionelle und authentische belgische Biere vom alten Stil; pures Malz und echter Hopfen – ohne Gewürze oder andere Zugaben.', 'Belgien', 'Gembloux'),
(449, 'BERTINCHAMPS BRUNE ', 50, 7, 'bertinchamps_brune.png', 'Dunkel gefärbt mit cremigem Schaum. Kaffee und Mokka, ergänzt durch Bitterschokolade und einem trockenen Finish. Ehrwürdig wie Vater Benoit Humblet.', 'Belgien', 'Gembloux'),
(450, 'BERTINCHAMPS TRIPLE', 50, 8, 'bertichamps_tripple.jpg', 'Ein bernsteinfarbener, körperbetonter Auftritt und eine Vielfalt von Frische, Hopfenbitterkeit und diskreten Karamellnoten machen es zum Erlebnis. ', 'Belgien', 'Gembloux');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bier`
--
ALTER TABLE `bier`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bier`
--
ALTER TABLE `bier`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=465;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
